---
inputs:
  image:
    description: image
    required: true
runs:
  using: 'composite'
  steps:
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: docker build -t ${{ inputs.image }} .
      shell: bash
    - uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.image }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
